### ISSUE TITLE
Mxe compile is failing at downloading libpng

### ISSUE THREAD

**Issue by gbrennon** [mxe/mxe#1631]
Hey!

I'm trying to build mxe with "make qt5", but it is failing on downloading libpng...

It seems to be the package version!

I've tried to change the package version on src/libpng.mk but I couldn't find the correct file checksum so the make could work.

here is the log: https://gist.github.com/gbrennon/5231bedd6104d996f79d3522a13eb3c6

**Comment by pavelvat** [comment]
https://github.com/mxe/mxe/commit/9990a0e0f3ee86c335932584f19eb14d01a04aee

**Comment by gbrennon** [comment]
Wow! Thank you @pavelvat 

I've tried to use sha1 and md5 checksum but this didn't work...

Which hash type did he use to generate the checksum?

**Comment by pavelvat** [comment]
>I've tried to use sha1 and md5 checksum but this didn't work...

You need just run:
```
git pull
```
>Which hash type did he use to generate the checksum?

sha256

**Comment by gbrennon** [comment]
Thank you @pavelvat !

**Comment by starius** [comment]
Glad to see that it was solved!

Some info for the record.

MXE downloads libpng from sourceforge which is known to serve 404 from time to time.
We have a backup of all packages in the cloud, but it has not been updated since September 2016:
http://lists.nongnu.org/archive/html/mingw-cross-env-list/2017-01/msg00005.html

I have added new backup option (gitlab repo) in ff36def5d393d8aa3c9253c00f5b61064acde913 few days ago.

**Comment by cgilles** [comment]
This is not solved : 

[download]  libjpeg-turbo
[build]     libjpeg-turbo            x86_64-w64-mingw32.shared
[done]      libjpeg-turbo            x86_64-w64-mingw32.shared                            21512 KiB      0m31.129s
[download]  libpng
MXE Warning! Downloading libpng from second URL.
MXE Warning! Downloading libpng from backup.

Download failed or wrong checksum of package libpng!
------------------------------------------------------------
--2017-01-19 17:25:13--  http://d1yihgixbnrglp.cloudfront.net/libpng%2D1%2E6%2E26%2Etar%2Exz
Resolving d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)... 52.85.221.217, 52.85.221.92, 52.85.221.44, ...
Connecting to d1yihgixbnrglp.cloudfront.net (d1yihgixbnrglp.cloudfront.net)|52.85.221.217|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-01-19 17:25:13 ERROR 404: Not Found.
Download failed!
------------------------------------------------------------
[log]      /mnt/data/5.x/project/bundles/mxe/build.win64/log/libpng-download

Makefile:488: recipe for target 'download-only-libpng-1.6.26.tar.xz' failed
make: *** [download-only-libpng-1.6.26.tar.xz] Error 1

**Comment by tonytheodore** [comment]
Looks like it's still trying to fetch the 1.6.26 version, try a `git pull` to get the latest version which should be available on three backup servers.
