### ISSUE TITLE
GNOME(mm) packages broken 

### ISSUE THREAD

**Issue by Janrupf** [mxe/mxe#2173]
I've just done a build from the latest GH source (e89d5d7ee2a059d676cb1d7ce8e7c2a0f28b70af) and tried to build a gtkmm app. It works fine on Linux, but building for Windows fails because some methods and classes are missing. Looks like this is because giomm is outdated. Examples:
```
application.cpp:70:138: error: no matching function for call to 'wrap(GSettingsSchemaSource*)'
                     Glib::wrap(g_settings_schema_source_new_from_directory("config", g_settings_schema_source_get_default(), FALSE, &err));
```
```
application.cpp:69:26: error: 'SettingsSchemaSource' is not a member of 'Gio'
             Glib::RefPtr<Gio::SettingsSchemaSource> schema_source =
```
That is not too bad because the calls can be replaced with their C version, but I would like to see the latest package in mxe.

And thanks for this wonderful thing, keep up the good work!

**Comment by Janrupf** [comment]
Note that this is because gklibmm is outdated

**Comment by Janrupf** [comment]
The problem keeps growing, I just updated the package versions the the makefiles and tried to build the new packages, but the makefiles do not work anymore. Looks like this affects a lot of gnome packages.

**Comment by tonytheodore** [comment]
Looks like gnome moved to gitlab and that will break most of the updaters, other problem is that it requires authentication and glibmm doesn't seem to be there. There's a [mirror on github](https://github.com/GNOME/glibmm) that seems more usable.

Recent versions of glibmm seem to need a posix toolchain, you could try manually updating a couple of packages:
```diff
diff --git a/src/glibmm.mk b/src/glibmm.mk
index 66b8335d..0637162d 100644
--- a/src/glibmm.mk
+++ b/src/glibmm.mk
@@ -4,8 +4,8 @@ PKG             := glibmm
 $(PKG)_WEBSITE  := https://www.gtkmm.org/
 $(PKG)_DESCR    := GLibmm
 $(PKG)_IGNORE   :=
-$(PKG)_VERSION  := 2.42.0
-$(PKG)_CHECKSUM := 985083d97378d234da27a7243587cc0d186897a4b2d3c1286f794089be1a3397
+$(PKG)_VERSION  := 2.56.0
+$(PKG)_CHECKSUM := 6e74fcba0d245451c58fc8a196e9d103789bc510e1eee1a9b1e816c5209e79a9
 $(PKG)_SUBDIR   := glibmm-$($(PKG)_VERSION)
 $(PKG)_FILE     := glibmm-$($(PKG)_VERSION).tar.xz
 $(PKG)_URL      := https://download.gnome.org/sources/glibmm/$(call SHORT_PKG_VERSION,$(PKG))/$($(PKG)_FILE)
diff --git a/src/libsigc++.mk b/src/libsigc++.mk
index e8fc542b..9974319f 100644
--- a/src/libsigc++.mk
+++ b/src/libsigc++.mk
@@ -3,8 +3,8 @@
 PKG             := libsigc++
 $(PKG)_WEBSITE  := https://libsigc.sourceforge.io/
 $(PKG)_IGNORE   :=
-$(PKG)_VERSION  := 2.4.0
-$(PKG)_CHECKSUM := 7593d5fa9187bbad7c6868dce375ce3079a805f3f1e74236143bceb15a37cd30
+$(PKG)_VERSION  := 2.10.0
+$(PKG)_CHECKSUM := f843d6346260bfcb4426259e314512b99e296e8ca241d771d21ac64f28298d81
 $(PKG)_SUBDIR   := libsigc++-$($(PKG)_VERSION)
 $(PKG)_FILE     := libsigc++-$($(PKG)_VERSION).tar.xz
 $(PKG)_URL      := https://download.gnome.org/sources/libsigc++/$(call SHORT_PKG_VERSION,$(PKG))/$($(PKG)_FILE)
```
 and building with:
```
make glibmm MXE_TARGETS=i686-w64-mingw32.static.posix
```

**Comment by tonytheodore** [comment]
That gets a little further but still fails eventually - probably glib needs to be updated also.

**Comment by Janrupf** [comment]
Yeah, I'm experimenting with it a lot and it looks like everything is completly broken unless you build shared with posix and just default makefiles. All these libraries need a big update. Maybe ship a shell script for parsing libs from here: download.gnome.org/sources/.

**Comment by Janrupf** [comment]
Maby this helps:
![gtkmm-3 0_deps](https://user-images.githubusercontent.com/25827180/43720854-8e7de864-9991-11e8-89f4-1ef337ddb52a.png)

**Comment by Janrupf** [comment]
More and more issues Oo... The MXE gcc doesn't accept MSVC format like "I64u" where as the system one does.

**Comment by tonytheodore** [comment]
See #2174 for a start on glib et al. updates, it's always the hardest package to build consistently across platforms and keep updated for the patches we do. Updates also break things (see #2168), so it's hard to know what the middle ground is.

It would be great if you could help out with testing the updates - I'm unfamiliar with most of the packages so [removing something like one of the patches](https://github.com/mxe/mxe/pull/2174/commits/761bbe85ed6ee1fcde31ed94121e754774981dd5#diff-2e1343f8ff95dd71ae488d7548256b41L171) needs someone to verify. To me it looks like [those sections were completely reworked](https://github.com/GNOME/glib/commit/cce29579389e892eb263d8507a71b3b3ca7433bb#diff-38053c5e4dd5ac732b58debdbdf494c4), but I have no real way to tell.
