### ISSUE TITLE
Add "wasapi" support for PortAudio

### ISSUE THREAD

**Issue by mgeier** [mxe/mxe#715]
I already asked this on the MXE mailing list (http://lists.gnu.org/archive/html/mingw-cross-env-list/2015-05/msg00012.html) and on the PortAudio mailing list (http://music.columbia.edu/pipermail/portaudio/2015-June/016804.html).
Since I didn't get a response, I'm trying it here ...

It would be great to enable "wasapi" support for Portaudio.
I tried this by changing the `--with-winapi` option in `src/portaudio.mk` from

    --with-winapi=wmme,directx

to

    --with-winapi=wasapi

Sadly, this doesn't compile:

```
$ make portaudio MXE_TARGETS=i686-w64-mingw32.static
```

An excerpt from `log/portaudio`:

```
src/hostapi/wasapi/pa_win_wasapi.c:262:66: error: unknown type name 'AVRT_PRIORITY'
 typedef BOOL   (WINAPI *FAvSetMmThreadPriority)          (HANDLE,AVRT_PRIORITY);
                                                                  ^
src/hostapi/wasapi/pa_win_wasapi.c:270:1: error: unknown type name 'FAvSetMmThreadPriority'
 FAvSetMmThreadPriority           pAvSetMmThreadPriority = NULL;
 ^
src/hostapi/wasapi/pa_win_wasapi.c:336:5: error: unknown type name 'IMMDevice'
     IMMDevice *device;
     ^
src/hostapi/wasapi/pa_win_wasapi.c:345:5: error: unknown type name 'EDataFlow'
     EDataFlow flow;
     ^
src/hostapi/wasapi/pa_win_wasapi.c:349:5: error: unknown type name 'REFERENCE_TIME'
     REFERENCE_TIME DefaultDevicePeriod;
     ^
src/hostapi/wasapi/pa_win_wasapi.c:350:5: error: unknown type name 'REFERENCE_TIME'
     REFERENCE_TIME MinimumDevicePeriod;
     ^
src/hostapi/wasapi/pa_win_wasapi.c:359:2: error: unknown type name 'EndpointFormFactor'
  EndpointFormFactor formFactor;
  ^
```

The list of errors goes on, but I guess it makes sense to tackle them one by one from the beginning.
I searched around for the first error, and it seems that `AVRT_PRIORITY` has something to do with the file `usr/i686-w64-mingw32.static/include/avrt.h` which ends up in my build tree.

How can I check if this is included in the right places?
If it's not, how can I add it?

Any ideas?

**Comment by TimothyGu** [comment]
First, why would you remove `wmme,directx`?

**Comment by TimothyGu** [comment]
> How can I check if this is included in the right places?

Well, look at the sources :)

The errors are coming from src/hostapi/wasapi/pa_win_wasapi.c, so you should take a look at tmp-portaudio-blahblah/portaudio-blah/src/hostapi/wasapi/pa_win_wasapi.c.

When you do that you can see that:

```c
#include <Avrt.h>
```

is in one place, under

```c
#if defined(_MSC_VER) && (_MSC_VER >= 1400)
```

Further grepping shows that at line 87 there is:

```c
#ifndef NTDDI_VERSION
// [...]
	#ifndef _AVRT_ //<< fix MinGW dummy compile by defining missing type: AVRT_PRIORITY
        typedef enum _AVRT_PRIORITY
        {
            AVRT_PRIORITY_LOW = -1,
            AVRT_PRIORITY_NORMAL,
            AVRT_PRIORITY_HIGH,
            AVRT_PRIORITY_CRITICAL
        } AVRT_PRIORITY, *PAVRT_PRIORITY;
	#endif
```

Based on all the other errors related to other APIs present in `mmdeviceapi.h` et al., and those headers are supposed to be included in `#ifndef NTDDI_VERSION` as well, I would guess that `NTDDI_VERSION` is defined. You can use an `#error` or two to find out if that is the case.

If my guess is correct, you can do whatever you need to to get those headers included correctly. I would just move those `#include`s to outside the `#ifndef`, and if that doesn't work paste the log here and I'll figure something out :)

(Yes porting to Windows is this tedious, especially when these projects add shims for old mingw versions that don't implement the APIs correctly and you have to either remove these shims or add proper configure checks detecting broken mingws… ugh)

**Comment by mgeier** [comment]
> First, why would you remove `wmme,directx`?

Sorry for the confusion, I removed this only while playing around, in the end I want to use `wmme,directx,wdmks,wasapi,asio`.

**Comment by mgeier** [comment]
Thanks a lot for your help, I tried some things but it doesn't work yet.

I hope you can give me some more hints.
This is what I did:

I added `#include <avrt.h>` (since it didn't work with capital "A"), which led to this error:

```
src/hostapi/wasapi/pa_win_wasapi.c:349:5: error: unknown type name 'IMMDevice'
     IMMDevice *device;
```

Then I added `#include <mmdeviceapi.h>`, which led to this error:

```
.../usr/i686-w64-mingw32.static/include/rpcndr.h:15:2: error: #error incorrect <rpcndr.h> version. Use the header that matches with the MIDL compiler.
```

In a desperate attempt to work around this, I added `#define _REQUIRED_RPCNDR_H_VERSION__ 0`, which led to this:

```
./src/hostapi/wasapi/mingw-include/propidl.h:1005:81: error: unknown type name 'STATPROPSTG'
     /* [length_is][size_is][out] */ __RPC__out_ecount_part(celt, *pceltFetched) STATPROPSTG *rgelt,
                                                                                 ^
```

It turns out that `STATPROPSTG` is defined in `src/hostapi/wasapi/mingw-include/propidl.h` within an `#ifdef WIN64` section, so I just removed the `#ifdef`.

New error:

```
src/hostapi/wasapi/pa_win_wasapi.c:361:5: error: unknown type name 'REFERENCE_TIME'
     REFERENCE_TIME DefaultDevicePeriod;
     ^
```

So I added `#include <strmif.h>`:

```
src/hostapi/wasapi/pa_win_wasapi.c:425:5: error: unknown type name 'IAudioClient'
     IAudioClient        *clientParent;
     ^
```

After adding `#include <audioclient.h>`:

```
src/hostapi/wasapi/pa_win_wasapi.c:478:5: error: unknown type name 'IAudioEndpointVolume'
     IAudioEndpointVolume      *inVol;
     ^
```

After `#include <endpointvolume.h>`:

```
src/hostapi/wasapi/pa_win_wasapi.c:1252:33: error: storage size of 'value' isn't known
                     PROPVARIANT value;
```

This is where I'm stuck.

There is a definition of `PROPVARIANT` in `src/hostapi/wasapi/mingw-include/propidl.h`, but I don't know what to do for it to be found.

As you can see, I have no idea what I'm doing here, probably you can give me some more hints how to proceed?

In the meantime, there were some warnings, I don't know if they are relevant:

```
src/hostapi/wasapi/pa_win_wasapi.c:67:0: warning: "__REQUIRED_RPCNDR_H_VERSION__" redefined
  #define __REQUIRED_RPCNDR_H_VERSION__ 0
 ^
In file included from src/hostapi/wasapi/pa_win_wasapi.c:65:0:
.../usr/i686-w64-mingw32.static/include/strmif.h:4:0: note: this is the location of the previous definition
 #define __REQUIRED_RPCNDR_H_VERSION__ 475
 ^
In file included from src/hostapi/wasapi/pa_win_wasapi.c:68:0:
./src/hostapi/wasapi/mingw-include/audioclient.h:1133:0: warning: "FACILITY_AUDCLNT" redefined
 #define FACILITY_AUDCLNT 0x889
 ^
In file included from .../usr/i686-w64-mingw32.static/include/winbase.h:2377:0,
                 from .../usr/i686-w64-mingw32.static/include/windows.h:70,
                 from src/hostapi/wasapi/pa_win_wasapi.c:46:
.../usr/i686-w64-mingw32.static/include/winerror.h:42:0: note: this is the location of the previous definition
 #define FACILITY_AUDCLNT 2185
 ^
```

**Comment by TimothyGu** [comment]
Ugh this kinda sucks. Investigating.

**Comment by TimothyGu** [comment]
Fixed. The important part is this patch: https://github.com/mxe/mxe/blob/master/src/portaudio-1-fixes.patch#L88-L132

It does a few things:

- it removes the buggy mingw-includes directory from inclusion path
- it makes mingw-w64 fall into the same code path as MSVC simply because mingw-w64 is compatible enough to MSVC now
- it fixes header name capitalization
- it corrects the win32 API usage by reordering headers and including functiondiscoverykeys_devpkey.h

**Comment by mgeier** [comment]
Thanks a lot, you're the best!

I still get a little error during patching, see #746.
